# Generated by Django 4.2.16 on 2026-01-18 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_avatar_url_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_transac_5011c8_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='billing_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='billing_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='esewa_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='esewa_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('OTHER', 'Other')], default='STRIPE', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription_tier',
            field=models.CharField(blank=True, choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='NPR', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('subscription', 'Subscription'), ('withdrawal', 'Withdrawal')], default='payment', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['id'], name='transaction_id_399ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_method'], name='transaction_payment_afdbde_idx'),
        ),
    ]
