# Generated by Django 4.2.16 on 2026-01-28 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_remove_transaction_transaction_transac_5011c8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='FREE', help_text="User's current subscription tier", max_length=20),
        ),
        migrations.CreateModel(
            name='PremiumSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='FREE', help_text='Subscription tier (FREE, PRO, ENTERPRISE)', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended')], default='INACTIVE', help_text='Current subscription status', max_length=20)),
                ('billing_cycle_start', models.DateTimeField(blank=True, help_text='When current billing cycle started', null=True)),
                ('billing_cycle_end', models.DateTimeField(blank=True, help_text='When current billing cycle ends', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Premium Subscription',
                'verbose_name_plural': 'Premium Subscriptions',
                'db_table': 'premium_subscriptions',
            },
        ),
    ]
