# Generated by Django 4.2.16 on 2026-01-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_premiumsubscription_apikey_billinghistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinghistory',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='billinghistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='premiumsubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='APIKey',
        ),
        migrations.DeleteModel(
            name='BillingHistory',
        ),
        migrations.DeleteModel(
            name='PremiumSubscription',
        ),
    ]
